# Experiment Analysis

In [186]:
import pandas as pd
import time
pd.set_option('display.max_columns',None)
df = pd.read_parquet('e_100K.parquet')
df

,experiment,val_loss,val_recall,val_precision,val_ndcg,test_loss,test_recall,test_precision,test_ndcg,optim_time,train_time,infer_time,users,items,train_edges,val_edges,test_edges,n_layers,embedding_dim,lr,lambda_val,batch_size,optimizer,train_losses,val_losses
0,e_100K_full,0.160351,0.059953,0.024020,0.044361,0.159969,0.058804,0.023311,0.040978,1211.563133,26.408738,0.082194,609,7758,65410,8176,8177,2,128,0.038537,0.000340,712,RMSprop,"[0.6911738514900208, 0.1875438690185547, 0.189...","[0.2603127062320709, 0.2087138593196869, 0.190..."
1,e_100K_1c1dcs,0.149292,0.038212,0.016014,0.027586,0.149897,0.038326,0.016554,0.028808,2278.382063,44.488821,0.082827,602,7740,53072,8176,8177,3,256,0.015843,0.000121,1414,RMSprop,"[0.6894171833992004, 0.08324895054101944, 0.08...","[0.3682708144187927, 0.15562553703784943, 0.14..."
2,e_100K_1c1dcs_rand1,0.236874,0.081947,0.035179,0.059076,0.238612,0.084777,0.039189,0.066072,919.071695,28.538728,0.089030,609,7188,53072,8176,8177,1,256,0.008025,0.000825,4026,RMSprop,"[0.6849004030227661, 0.08707093447446823, 0.08...","[0.5779886245727539, 0.2112463265657425, 0.225..."
3,e_100K_1c1dcs_rand2,0.241672,0.072799,0.038842,0.059257,0.240546,0.078234,0.039274,0.062040,475.218402,23.414483,0.086191,609,7169,53072,8176,8177,1,96,0.000149,0.000204,3497,RMSprop,"[0.6883674263954163, 0.6642707586288452, 0.602...","[0.6659068465232849, 0.6492341756820679, 0.600..."
4,e_100K_1c1dcs_rand3,0.212063,0.055485,0.025043,0.040611,0.216072,0.053049,0.024578,0.041195,1216.786829,21.845359,0.082431,609,7120,53072,8176,8177,1,64,0.085213,0.000311,3650,RMSprop,"[0.6904571056365967, 0.30040550231933594, 0.21...","[0.36336684226989746, 0.4566064178943634, 0.44..."
5,e_100K_1c1dcs_rand4,0.208237,0.047399,0.018910,0.035544,0.204388,0.044399,0.017483,0.031554,1486.897050,25.074050,0.079911,609,7170,53072,8176,8177,2,64,0.088859,0.000973,2943,RMSprop,"[0.6932864189147949, 0.1923486292362213, 0.168...","[0.2994730770587921, 0.24459412693977356, 0.22..."
6,e_100K_1c1dcs_rand5,0.243777,0.080121,0.036712,0.062350,0.248393,0.078118,0.039020,0.063765,726.769576,26.970877,0.088456,609,7156,53072,8176,8177,1,256,0.003821,0.001317,994,Adam,"[0.6890922784805298, 0.1713433861732483, 0.120...","[0.6330972909927368, 0.24790754914283752, 0.22..."
7,e_100K_1c2dcs,0.274358,0.065246,0.039267,0.058322,0.267710,0.063702,0.042399,0.062857,958.885545,22.856713,0.084758,608,7752,54402,8176,8177,1,128,0.019762,0.002208,2009,Adam,"[0.6955881118774414, 0.1569587141275406, 0.165...","[0.6631136536598206, 0.2805919349193573, 0.279..."
8,e_100K_1c2dcs_rand1,0.157009,0.050365,0.019165,0.035149,0.164600,0.039055,0.015963,0.029295,1291.043661,32.226701,0.082611,609,7247,54402,8176,8177,3,128,0.049024,0.000152,1537,RMSprop,"[0.6911002397537231, 0.15078763663768768, 0.09...","[0.2069285660982132, 0.1664951890707016, 0.148..."
9,e_100K_1c2dcs_rand2,0.248956,0.083590,0.039693,0.063717,0.239475,0.092167,0.041216,0.071605,898.041399,28.894946,0.089959,609,7235,54402,8176,8177,1,256,0.014195,0.001260,4006,RMSprop,"[0.6899763345718384, 0.11388743668794632, 0.11...","[0.5129003524780273, 0.23733696341514587, 0.24..."
10,e_100K_1c2dcs_rand3,0.201747,0.076316,0.033731,0.060773,0.202151,0.080885,0.033446,0.060491,1015.506632,28.196951,0.089631,609,7228,54402,8176,8177,1,256,0.014355,0.000291,2401,RMSprop,"[0.6821906566619873, 0.09335573762655258, 0.07...","[0.48594239354133606, 0.1921413689851761, 0.17..."
11,e_100K_1c2dcs_rand4,0.148833,0.031999,0.014480,0.025133,0.143747,0.032249,0.013767,0.021545,552.305738,37.356084,0.082148,609,7253,54402,8176,8177,2,256,0.001104,0.000031,3728,Adam,"[0.685907781124115, 0.22856037318706512, 0.146...","[0.6474504470825195, 0.23891936242580414, 0.19..."
12,e_100K_1c2dcs_rand5,0.235556,0.083785,0.035179,0.062810,0.238129,0.090425,0.039865,0.067286,946.948788,20.682649,0.087010,609,7249,54402,8176,8177,1,128,0.020147,0.000849,3420,RMSprop,"[0.6897034645080566, 0.10552801936864853, 0.10...","[0.5313901305198669, 0.22833117842674255, 0.23..."
13,e_100K_1c3dcs,0.159891,0.051002,0.025298,0.037581,0.166399,0.064896,0.027534,0.048652,513.314020,29.527459,0.084748,608,7758,56335,8176,8177,1,256,0.007680,0.000079,2450,Adam,"[0.6825181245803833, 0.08419260382652283, 0.07...","[0.6226349472999573, 0.17459750175476074, 0.15..."
14,e_100K_1c3dcs_rand1,0.259279,0.082079,0.038927,0.064469,0.262466,0.092891,0.044426,0.069923,733.353635,30.246116,0.089462,609,7345,56335,8176,8177,1,256,0.011239,0.002114,2085,RMSprop,"[0.6950250267982483, 0.14850008487701416, 0.12...","[0.5638154745101929, 0.2776358723640442, 0.274..."
15,e_100K_1c3dcs_rand2,0.248117,0.083364,0.036627,0.063100,0.248847,0.087773,0.040963,0.069194,1220.502762,23.335112,0.086763,609,7339,56335,8176,8177,1,128,0.020128,0.001385,2743,RMSprop,"[0.6919812560081482, 0.1294843852519989, 0.129...","[0.534211277961731, 0.2483363151550293, 0.2473..."
16,e_100K_1c3dcs_rand3,0.235220,0.089336,0.039438,0.070900,0.223220,0.090883,0.041807,0.071625,771.660719,26.733949,0.089461,609,7355,56335,8176,8177,1,256,0.009386,0.000838,1370,RMSprop,"[0.6873987913131714, 0.10681069642305374, 0.11...","[0.5677849650382996, 0.2243216186761856, 0.222..."
17,e_100K_1c3dcs_rand4,0.317771,0.061914,0.035605,0.052540,0.309991,0.068314,0.037922,0.057293,1558.536505,20.511499,0.085496,609,7356,56335,8176,8177,1,96,0.036828,0.005849,986,RMSprop,"[0.7058121562004089, 0.29074180126190186, 0.25...","[0.6039783954620361, 0.406238853931427, 0.3731..."
18,e_100K_1c3dcs_rand5,0.422611,0.047102,0.027002,0.041239,0.428490,0.049450,0.026689,0.043728,1587.845680,32.284070,0.083652,609,7322,56335,8176,8177,3,128,0.000029,0.000072,680,Adam,"[0.6909158229827881, 0.6901383399963379, 0.689...","[0.6747211217880249, 0.6742778420448303, 0.673..."

In [187]:
key = ['experiment']
val_features = ['val_loss','val_recall','val_precision','val_ndcg' ]
test_features = ['test_loss','test_recall','test_precision','test_ndcg']
time_features = ['optim_time','train_time','infer_time']
edge_features =  ['train_edges']
numerical_features = val_features + test_features
categorical_features = ['n_layers','embedding_dim','lr','lambda_val','batch_size', 'optimizer']

random_experiments_stats = df.copy()
random_experiments_stats = random_experiments_stats[key + numerical_features + time_features + edge_features + categorical_features]
random_experiments_stats['experiment'] = random_experiments_stats['experiment'].apply(lambda x: x[:-1] if '_rand' in x else x)
random_experiments_stats

,experiment,val_loss,val_recall,val_precision,val_ndcg,test_loss,test_recall,test_precision,test_ndcg,optim_time,train_time,infer_time,train_edges,n_layers,embedding_dim,lr,lambda_val,batch_size,optimizer
0,e_100K_full,0.160351,0.059953,0.024020,0.044361,0.159969,0.058804,0.023311,0.040978,1211.563133,26.408738,0.082194,65410,2,128,0.038537,0.000340,712,RMSprop
1,e_100K_1c1dcs,0.149292,0.038212,0.016014,0.027586,0.149897,0.038326,0.016554,0.028808,2278.382063,44.488821,0.082827,53072,3,256,0.015843,0.000121,1414,RMSprop
2,e_100K_1c1dcs_rand,0.236874,0.081947,0.035179,0.059076,0.238612,0.084777,0.039189,0.066072,919.071695,28.538728,0.089030,53072,1,256,0.008025,0.000825,4026,RMSprop
3,e_100K_1c1dcs_rand,0.241672,0.072799,0.038842,0.059257,0.240546,0.078234,0.039274,0.062040,475.218402,23.414483,0.086191,53072,1,96,0.000149,0.000204,3497,RMSprop
4,e_100K_1c1dcs_rand,0.212063,0.055485,0.025043,0.040611,0.216072,0.053049,0.024578,0.041195,1216.786829,21.845359,0.082431,53072,1,64,0.085213,0.000311,3650,RMSprop
5,e_100K_1c1dcs_rand,0.208237,0.047399,0.018910,0.035544,0.204388,0.044399,0.017483,0.031554,1486.897050,25.074050,0.079911,53072,2,64,0.088859,0.000973,2943,RMSprop
6,e_100K_1c1dcs_rand,0.243777,0.080121,0.036712,0.062350,0.248393,0.078118,0.039020,0.063765,726.769576,26.970877,0.088456,53072,1,256,0.003821,0.001317,994,Adam
7,e_100K_1c2dcs,0.274358,0.065246,0.039267,0.058322,0.267710,0.063702,0.042399,0.062857,958.885545,22.856713,0.084758,54402,1,128,0.019762,0.002208,2009,Adam
8,e_100K_1c2dcs_rand,0.157009,0.050365,0.019165,0.035149,0.164600,0.039055,0.015963,0.029295,1291.043661,32.226701,0.082611,54402,3,128,0.049024,0.000152,1537,RMSprop
9,e_100K_1c2dcs_rand,0.248956,0.083590,0.039693,0.063717,0.239475,0.092167,0.041216,0.071605,898.041399,28.894946,0.089959,54402,1,256,0.014195,0.001260,4006,RMSprop
10,e_100K_1c2dcs_rand,0.201747,0.076316,0.033731,0.060773,0.202151,0.080885,0.033446,0.060491,1015.506632,28.196951,0.089631,54402,1,256,0.014355,0.000291,2401,RMSprop
11,e_100K_1c2dcs_rand,0.148833,0.031999,0.014480,0.025133,0.143747,0.032249,0.013767,0.021545,552.305738,37.356084,0.082148,54402,2,256,0.001104,0.000031,3728,Adam
12,e_100K_1c2dcs_rand,0.235556,0.083785,0.035179,0.062810,0.238129,0.090425,0.039865,0.067286,946.948788,20.682649,0.087010,54402,1,128,0.020147,0.000849,3420,RMSprop
13,e_100K_1c3dcs,0.159891,0.051002,0.025298,0.037581,0.166399,0.064896,0.027534,0.048652,513.314020,29.527459,0.084748,56335,1,256,0.007680,0.000079,2450,Adam
14,e_100K_1c3dcs_rand,0.259279,0.082079,0.038927,0.064469,0.262466,0.092891,0.044426,0.069923,733.353635,30.246116,0.089462,56335,1,256,0.011239,0.002114,2085,RMSprop
15,e_100K_1c3dcs_rand,0.248117,0.083364,0.036627,0.063100,0.248847,0.087773,0.040963,0.069194,1220.502762,23.335112,0.086763,56335,1,128,0.020128,0.001385,2743,RMSprop
16,e_100K_1c3dcs_rand,0.235220,0.089336,0.039438,0.070900,0.223220,0.090883,0.041807,0.071625,771.660719,26.733949,0.089461,56335,1,256,0.009386,0.000838,1370,RMSprop
17,e_100K_1c3dcs_rand,0.317771,0.061914,0.035605,0.052540,0.309991,0.068314,0.037922,0.057293,1558.536505,20.511499,0.085496,56335,1,96,0.036828,0.005849,986,RMSprop
18,e_100K_1c3dcs_rand,0.422611,0.047102,0.027002,0.041239,0.428490,0.049450,0.026689,0.043728,1587.845680,32.284070,0.083652,56335,3,128,0.000029,0.000072,680,Adam

In [192]:
aggregations = { x : ['mean','std'] for x in numerical_features + time_features}
aggregations.update({ x : ['mean'] for x in edge_features} )
aggregations.update({ x : ['unique'] for x in categorical_features} )


result = random_experiments_stats.groupby(key, as_index=False).agg(aggregations)
result.columns = ["_".join(col).strip() for col in result.columns.values]
result.columns = [ x[:-1] if x[-1]== '_' else x for x in result.columns]
result.fillna(0, inplace=True)
result

,experiment,val_loss_mean,val_loss_std,val_recall_mean,val_recall_std,val_precision_mean,val_precision_std,val_ndcg_mean,val_ndcg_std,test_loss_mean,test_loss_std,test_recall_mean,test_recall_std,test_precision_mean,test_precision_std,test_ndcg_mean,test_ndcg_std,optim_time_mean,optim_time_std,train_time_mean,train_time_std,infer_time_mean,infer_time_std,train_edges_mean,n_layers_unique,embedding_dim_unique,lr_unique,lambda_val_unique,batch_size_unique,optimizer_unique
0,e_100K_1c1dcs,0.149292,0.000000,0.038212,0.000000,0.016014,0.000000,0.027586,0.000000,0.149897,0.000000,0.038326,0.000000,0.016554,0.000000,0.028808,0.000000,2278.382063,0.000000,44.488821,0.000000,0.082827,0.000000,53072.0,[3],[256],[0.015843188754113408],[0.00012134581337554393],[1414],[RMSprop]
1,e_100K_1c1dcs_rand,0.228525,0.017013,0.067550,0.015366,0.030937,0.008562,0.051368,0.012333,0.229602,0.018526,0.067715,0.017809,0.031909,0.010243,0.052925,0.015555,964.948710,398.284535,25.168699,2.680287,0.085204,0.003934,53072.0,"[1, 2]","[256, 96, 64]","[0.008024924879139504, 0.00014909483627344864,...","[0.0008251914516064217, 0.0002042552923095513,...","[4026, 3497, 3650, 2943, 994]","[RMSprop, Adam]"
2,e_100K_1c2dcs,0.274358,0.000000,0.065246,0.000000,0.039267,0.000000,0.058322,0.000000,0.267710,0.000000,0.063702,0.000000,0.042399,0.000000,0.062857,0.000000,958.885545,0.000000,22.856713,0.000000,0.084758,0.000000,54402.0,[1],[128],[0.019761860326784987],[0.002208379974935007],[2009],[Adam]
3,e_100K_1c2dcs_rand,0.198420,0.045049,0.065211,0.023074,0.028450,0.010965,0.049516,0.018070,0.197621,0.043029,0.066956,0.028998,0.028851,0.013124,0.050044,0.022989,940.769243,265.068668,29.471466,6.102430,0.086272,0.003736,54402.0,"[3, 1, 2]","[128, 256]","[0.0490240506718616, 0.014194980064888441, 0.0...","[0.00015218745930804358, 0.001260336724852014,...","[1537, 4006, 2401, 3728, 3420]","[RMSprop, Adam]"
4,e_100K_1c3dcs,0.159891,0.000000,0.051002,0.000000,0.025298,0.000000,0.037581,0.000000,0.166399,0.000000,0.064896,0.000000,0.027534,0.000000,0.048652,0.000000,513.314020,0.000000,29.527459,0.000000,0.084748,0.000000,56335.0,[1],[256],[0.007679842727911722],[7.902400968173864e-05],[2450],[Adam]
5,e_100K_1c3dcs_rand,0.296600,0.077198,0.072759,0.017678,0.035520,0.005019,0.058450,0.011662,0.294603,0.081216,0.077862,0.018655,0.038361,0.006926,0.062353,0.011859,1174.379860,411.504700,26.622149,4.830829,0.086967,0.002532,56335.0,"[1, 3]","[256, 128, 96]","[0.011239144850338915, 0.020128264011354494, 0...","[0.0021144786935499127, 0.001384797324277196, ...","[2085, 2743, 1370, 986, 680]","[RMSprop, Adam]"
6,e_100K_full,0.160351,0.000000,0.059953,0.000000,0.024020,0.000000,0.044361,0.000000,0.159969,0.000000,0.058804,0.000000,0.023311,0.000000,0.040978,0.000000,1211.563133,0.000000,26.408738,0.000000,0.082194,0.000000,65410.0,[2],[128],[0.0385365130277391],[0.00034006815493167584],[712],[RMSprop]

In [189]:
result_viewable = result.copy()

for col in numerical_features:
    result_viewable[col] = result_viewable[[col+'_mean',col+'_std']].apply(lambda x: '{:,.4f}'.format(x[col+'_mean']) if x[col+'_std'] ==0 else '{:,.4f}'.format(x[col+'_mean']) + ' \u00B1 ' +  '{:,.4f}'.format(x[col+'_std']), axis=1)
    result_viewable.drop([col+'_mean', col+'_std'], axis=1, inplace=True)

for col in time_features:
    result_viewable[col] = result_viewable[[col+'_mean',col+'_std']].apply(lambda x: str(time.strftime("%H:%M:%S", time.gmtime(x[col+'_mean']))) if x[col+'_std'] ==0 else str(time.strftime("%H:%M:%S", time.gmtime(x[col+'_mean']))) + ' \u00B1 ' +  str(time.strftime("%H:%M:%S", time.gmtime(x[col+'_std']))), axis=1)
    result_viewable.drop([col+'_mean', col+'_std'], axis=1, inplace=True)

result_viewable = result_viewable[key + numerical_features + [x +'_mean' for x in edge_features] + time_features + [x +'_unique' for x in categorical_features] ]

In [190]:
result_viewable

,experiment,val_loss,val_recall,val_precision,val_ndcg,test_loss,test_recall,test_precision,test_ndcg,train_edges_mean,optim_time,train_time,infer_time,n_layers_unique,embedding_dim_unique,lr_unique,lambda_val_unique,batch_size_unique,optimizer_unique
0,e_100K_1c1dcs,0.1493,0.0382,0.0160,0.0276,0.1499,0.0383,0.0166,0.0288,53072.0,00:37:58,00:00:44,00:00:00,[3],[256],[0.015843188754113408],[0.00012134581337554393],[1414],[RMSprop]
1,e_100K_1c1dcs_rand,0.2285 ± 0.0170,0.0676 ± 0.0154,0.0309 ± 0.0086,0.0514 ± 0.0123,0.2296 ± 0.0185,0.0677 ± 0.0178,0.0319 ± 0.0102,0.0529 ± 0.0156,53072.0,00:16:04 ± 00:06:38,00:00:25 ± 00:00:02,00:00:00 ± 00:00:00,"[1, 2]","[256, 96, 64]","[0.008024924879139504, 0.00014909483627344864,...","[0.0008251914516064217, 0.0002042552923095513,...","[4026, 3497, 3650, 2943, 994]","[RMSprop, Adam]"
2,e_100K_1c2dcs,0.2744,0.0652,0.0393,0.0583,0.2677,0.0637,0.0424,0.0629,54402.0,00:15:58,00:00:22,00:00:00,[1],[128],[0.019761860326784987],[0.002208379974935007],[2009],[Adam]
3,e_100K_1c2dcs_rand,0.1984 ± 0.0450,0.0652 ± 0.0231,0.0284 ± 0.0110,0.0495 ± 0.0181,0.1976 ± 0.0430,0.0670 ± 0.0290,0.0289 ± 0.0131,0.0500 ± 0.0230,54402.0,00:15:40 ± 00:04:25,00:00:29 ± 00:00:06,00:00:00 ± 00:00:00,"[3, 1, 2]","[128, 256]","[0.0490240506718616, 0.014194980064888441, 0.0...","[0.00015218745930804358, 0.001260336724852014,...","[1537, 4006, 2401, 3728, 3420]","[RMSprop, Adam]"
4,e_100K_1c3dcs,0.1599,0.0510,0.0253,0.0376,0.1664,0.0649,0.0275,0.0487,56335.0,00:08:33,00:00:29,00:00:00,[1],[256],[0.007679842727911722],[7.902400968173864e-05],[2450],[Adam]
5,e_100K_1c3dcs_rand,0.2966 ± 0.0772,0.0728 ± 0.0177,0.0355 ± 0.0050,0.0584 ± 0.0117,0.2946 ± 0.0812,0.0779 ± 0.0187,0.0384 ± 0.0069,0.0624 ± 0.0119,56335.0,00:19:34 ± 00:06:51,00:00:26 ± 00:00:04,00:00:00 ± 00:00:00,"[1, 3]","[256, 128, 96]","[0.011239144850338915, 0.020128264011354494, 0...","[0.0021144786935499127, 0.001384797324277196, ...","[2085, 2743, 1370, 986, 680]","[RMSprop, Adam]"
6,e_100K_full,0.1604,0.0600,0.0240,0.0444,0.1600,0.0588,0.0233,0.0410,65410.0,00:20:11,00:00:26,00:00:00,[2],[128],[0.0385365130277391],[0.00034006815493167584],[712],[RMSprop]

In [191]:
cols = result_viewable.columns

for token in ['_unique','_mean']:
    rename_dict = { x : x[:-len(token)] if token in x else x for x in cols }
    result_viewable.rename(rename_dict, axis=1, inplace=True)

result_viewable

,experiment,val_loss,val_recall,val_precision,val_ndcg,test_loss,test_recall,test_precision,test_ndcg,train_edges,optim_time,train_time,infer_time,n_layers,embedding_dim,lr,lambda_val,batch_size,optimizer
0,e_100K_1c1dcs,0.1493,0.0382,0.0160,0.0276,0.1499,0.0383,0.0166,0.0288,53072.0,00:37:58,00:00:44,00:00:00,[3],[256],[0.015843188754113408],[0.00012134581337554393],[1414],[RMSprop]
1,e_100K_1c1dcs_rand,0.2285 ± 0.0170,0.0676 ± 0.0154,0.0309 ± 0.0086,0.0514 ± 0.0123,0.2296 ± 0.0185,0.0677 ± 0.0178,0.0319 ± 0.0102,0.0529 ± 0.0156,53072.0,00:16:04 ± 00:06:38,00:00:25 ± 00:00:02,00:00:00 ± 00:00:00,"[1, 2]","[256, 96, 64]","[0.008024924879139504, 0.00014909483627344864,...","[0.0008251914516064217, 0.0002042552923095513,...","[4026, 3497, 3650, 2943, 994]","[RMSprop, Adam]"
2,e_100K_1c2dcs,0.2744,0.0652,0.0393,0.0583,0.2677,0.0637,0.0424,0.0629,54402.0,00:15:58,00:00:22,00:00:00,[1],[128],[0.019761860326784987],[0.002208379974935007],[2009],[Adam]
3,e_100K_1c2dcs_rand,0.1984 ± 0.0450,0.0652 ± 0.0231,0.0284 ± 0.0110,0.0495 ± 0.0181,0.1976 ± 0.0430,0.0670 ± 0.0290,0.0289 ± 0.0131,0.0500 ± 0.0230,54402.0,00:15:40 ± 00:04:25,00:00:29 ± 00:00:06,00:00:00 ± 00:00:00,"[3, 1, 2]","[128, 256]","[0.0490240506718616, 0.014194980064888441, 0.0...","[0.00015218745930804358, 0.001260336724852014,...","[1537, 4006, 2401, 3728, 3420]","[RMSprop, Adam]"
4,e_100K_1c3dcs,0.1599,0.0510,0.0253,0.0376,0.1664,0.0649,0.0275,0.0487,56335.0,00:08:33,00:00:29,00:00:00,[1],[256],[0.007679842727911722],[7.902400968173864e-05],[2450],[Adam]
5,e_100K_1c3dcs_rand,0.2966 ± 0.0772,0.0728 ± 0.0177,0.0355 ± 0.0050,0.0584 ± 0.0117,0.2946 ± 0.0812,0.0779 ± 0.0187,0.0384 ± 0.0069,0.0624 ± 0.0119,56335.0,00:19:34 ± 00:06:51,00:00:26 ± 00:00:04,00:00:00 ± 00:00:00,"[1, 3]","[256, 128, 96]","[0.011239144850338915, 0.020128264011354494, 0...","[0.0021144786935499127, 0.001384797324277196, ...","[2085, 2743, 1370, 986, 680]","[RMSprop, Adam]"
6,e_100K_full,0.1604,0.0600,0.0240,0.0444,0.1600,0.0588,0.0233,0.0410,65410.0,00:20:11,00:00:26,00:00:00,[2],[128],[0.0385365130277391],[0.00034006815493167584],[712],[RMSprop]